name: omero-guide-ilastik
channels:
  - anaconda
  - conda-forge
  - ilastik-forge
dependencies:
  - python==3.9.*
  - omero-py==5.19.*
  - pip
  - ipywidgets==7.8.5
  - ilastik-forge::ilastik==1.4.1b22
  - tornado==6.1
  - ipykernel==6.29.5
  - pip:
    - yapsy==1.12.2
    - itkwidgets==0.32.6
    - ome-zarr==0.9.0
